name: Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SourceMod
        uses: KatsuteTF/Workflows/actions/setup-sourcepawn@main
        with:
          sourcemod-version: "1.12"

      - name: Install TF2Attributes
        uses: KatsuteTF/Workflows/actions/curl@main
        with:
          url: https://raw.githubusercontent.com/FlaminSarge/tf2attributes/master/scripting/include/tf2attributes.inc
          file: addons/sourcemod/include/tf2attributes.inc

      - name: Install More Colors
        uses: KatsuteTF/Workflows/actions/curl@main
        with:
          url: https://raw.githubusercontent.com/DoctorMcKay/sourcemod-plugins/master/scripting/include/morecolors.inc
          file: addons/sourcemod/include/morecolors.inc

      - name: Compile Plugin
        run: |-
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_backstabdamage.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_crits.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_damage.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_example.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_exphs.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_gravity.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_healonhit.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_hsdamage.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_jump.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_meleedamage.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_meleeonly.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_primarydamage.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_scarybullets.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_secondarydamage.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_sentrydamage.sp
          spcomp -i addons/sourcemod/include addons/sourcemod/scripting/rrm_speed.sp

      - name: Deploy to GitHub Releases
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "*.smx"
          repo-token: ${{ secrets.GITHUB_TOKEN }}